const reuseMarkets = [
  {
    "id": "market-01",
    "name": "Mercatino Alba Adriatica",
    "region": "Abruzzo",
    "province": "TE",
    "city": "Alba Adriatica",
    "address": "Via G. Oberdan, 10",
    "cap": "64011",
    "mail": "albaadriatica@mercatopoli.it",
    "sqm": 700,
    "storeType": "Generalista",
    "itemsSold": 159,
    "kwhSaved": 2223,
    "co2Saved": 567,
    "treesEquivalent": 27,
    "reuseRate": 64,
    "categories": {
      "Arredo": 41,
      "Elettronica": 17,
      "Moda": 50,
      "Casa": 31,
      "Libri e giochi": 20
    }
  },
  {
    "id": "market-02",
    "name": "Mercatino Silvi Marina",
    "region": "Abruzzo",
    "province": "TE",
    "city": "Silvi Marina",
    "address": "Via Statale Adriatica Sud, 70",
    "cap": "64028",
    "mail": "info@portobellousato.it",
    "sqm": 1000,
    "storeType": "Generalista",
    "itemsSold": 171,
    "kwhSaved": 2620,
    "co2Saved": 668,
    "treesEquivalent": 32,
    "reuseRate": 73,
    "categories": {
      "Arredo": 56,
      "Elettronica": 19,
      "Moda": 36,
      "Casa": 46,
      "Libri e giochi": 14
    }
  },
  {
    "id": "market-03",
    "name": "Mercatino Vasto",
    "region": "Abruzzo",
    "province": "CH",
    "city": "Vasto",
    "address": "Circonvallazione Histoniense, 202h",
    "cap": "66054",
    "mail": "ch01@kece.it",
    "sqm": 400,
    "storeType": "Generalista",
    "itemsSold": 91,
    "kwhSaved": 1315,
    "co2Saved": 335,
    "treesEquivalent": 16,
    "reuseRate": 85,
    "categories": {
      "Arredo": 20,
      "Elettronica": 12,
      "Moda": 32,
      "Casa": 17,
      "Libri e giochi": 10
    }
  },
  {
    "id": "market-04",
    "name": "Mercatino Avezzano",
    "region": "Abruzzo",
    "province": "AQ",
    "city": "Avezzano",
    "address": "Via Fucino, 13",
    "cap": "67051",
    "mail": "guidocostantini@icloud.com",
    "sqm": 500,
    "storeType": "Generalista",
    "itemsSold": 132,
    "kwhSaved": 2393,
    "co2Saved": 610,
    "treesEquivalent": 29,
    "reuseRate": 73,
    "categories": {
      "Arredo": 35,
      "Elettronica": 28,
      "Moda": 36,
      "Casa": 29,
      "Libri e giochi": 4
    }
  },
  {
    "id": "market-05",
    "name": "Mercatino Potenza",
    "region": "Basilicata",
    "province": "PZ",
    "city": "Potenza",
    "address": "Via Isca del Pioppo, 34",
    "cap": "85100",
    "mail": "dbleonardo64@libero.it",
    "sqm": 0,
    "storeType": "Generalista",
    "itemsSold": 119,
    "kwhSaved": 1678,
    "co2Saved": 428,
    "treesEquivalent": 20,
    "reuseRate": 82,
    "categories": {
      "Arredo": 32,
      "Elettronica": 12,
      "Moda": 34,
      "Casa": 28,
      "Libri e giochi": 13
    }
  },
  {
    "id": "market-06",
    "name": "Mercatino Matera",
    "region": "Basilicata",
    "province": "MT",
    "city": "Matera",
    "address": "Via Moncenisio 5/7, 5",
    "cap": "75100",
    "mail": "paladinopaolo@gmail.com",
    "sqm": 1200,
    "storeType": "Generalista",
    "itemsSold": 154,
    "kwhSaved": 2350,
    "co2Saved": 599,
    "treesEquivalent": 29,
    "reuseRate": 63,
    "categories": {
      "Arredo": 41,
      "Elettronica": 21,
      "Moda": 39,
      "Casa": 35,
      "Libri e giochi": 18
    }
  },
  {
    "id": "market-07",
    "name": "Mercatino Reggio Calabria",
    "region": "Calabria",
    "province": "RC",
    "city": "Reggio Calabria",
    "address": "Via Padova, 7",
    "cap": "89029",
    "mail": "info@Portobellorc.com",
    "sqm": 0,
    "storeType": "Generalista",
    "itemsSold": 126,
    "kwhSaved": 2053,
    "co2Saved": 524,
    "treesEquivalent": 25,
    "reuseRate": 64,
    "categories": {
      "Arredo": 37,
      "Elettronica": 20,
      "Moda": 25,
      "Casa": 28,
      "Libri e giochi": 16
    }
  },
  {
    "id": "market-08",
    "name": "Mercatino Diamante",
    "region": "Calabria",
    "province": "CS",
    "city": "Diamante",
    "address": "Via Caravaggio, 1",
    "cap": "87023",
    "mail": "usato@loccasione.info",
    "sqm": 0,
    "storeType": "Generalista",
    "itemsSold": 95,
    "kwhSaved": 1499,
    "co2Saved": 382,
    "treesEquivalent": 18,
    "reuseRate": 69,
    "categories": {
      "Arredo": 26,
      "Elettronica": 15,
      "Moda": 22,
      "Casa": 17,
      "Libri e giochi": 15
    }
  },
  {
    "id": "market-09",
    "name": "Mercatino Crotone",
    "region": "Calabria",
    "province": "KR",
    "city": "Crotone",
    "address": "Loc. Poggio Pudano S.S. 106 Km 242",
    "cap": "88900",
    "mail": "affarefattousato@gmail.com",
    "sqm": 0,
    "storeType": "Generalista",
    "itemsSold": 103,
    "kwhSaved": 1644,
    "co2Saved": 419,
    "treesEquivalent": 20,
    "reuseRate": 66,
    "categories": {
      "Arredo": 28,
      "Elettronica": 16,
      "Moda": 26,
      "Casa": 22,
      "Libri e giochi": 11
    }
  },
  {
    "id": "market-10",
    "name": "Mercatino Cosenza",
    "region": "Calabria",
    "province": "CS",
    "city": "Cosenza",
    "address": "Via Piave, 74",
    "cap": "87100",
    "mail": "mercatinocscentro@libero.it",
    "sqm": 0,
    "storeType": "Generalista",
    "itemsSold": 163,
    "kwhSaved": 2467,
    "co2Saved": 629,
    "treesEquivalent": 30,
    "reuseRate": 84,
    "categories": {
      "Arredo": 32,
      "Elettronica": 25,
      "Moda": 48,
      "Casa": 39,
      "Libri e giochi": 19
    }
  },
  {
    "id": "market-11",
    "name": "Mercatino Rossano",
    "region": "Calabria",
    "province": "CS",
    "city": "Rossano",
    "address": "II trav. Viale Margherita, 180/A",
    "cap": "87067",
    "mail": "nientedinuovorossano@gmail.com",
    "sqm": 300,
    "storeType": "Generalista",
    "itemsSold": 142,
    "kwhSaved": 2223,
    "co2Saved": 567,
    "treesEquivalent": 27,
    "reuseRate": 80,
    "categories": {
      "Arredo": 30,
      "Elettronica": 25,
      "Moda": 46,
      "Casa": 21,
      "Libri e giochi": 20
    }
  },
  {
    "id": "market-12",
    "name": "Mercatino Cosenza",
    "region": "Calabria",
    "province": "CS",
    "city": "Cosenza",
    "address": "via Tommasi, 29",
    "cap": "87100",
    "mail": "esubitoebay@gmail.com",
    "sqm": 0,
    "storeType": "Generalista",
    "itemsSold": 131,
    "kwhSaved": 1896,
    "co2Saved": 483,
    "treesEquivalent": 23,
    "reuseRate": 63,
    "categories": {
      "Arredo": 28,
      "Elettronica": 17,
      "Moda": 39,
      "Casa": 31,
      "Libri e giochi": 16
    }
  },
  {
    "id": "market-13",
    "name": "Mercatino San Giorgio a Cremano",
    "region": "Da classificare",
    "province": "",
    "city": "San Giorgio a Cremano",
    "address": "Via San Martino, 9",
    "cap": "80046",
    "mail": "sangiorgioacremano@mercatopoli.it",
    "sqm": 600,
    "storeType": "Generalista",
    "itemsSold": 156,
    "kwhSaved": 2440,
    "co2Saved": 622,
    "treesEquivalent": 30,
    "reuseRate": 80,
    "categories": {
      "Arredo": 43,
      "Elettronica": 22,
      "Moda": 42,
      "Casa": 36,
      "Libri e giochi": 13
    }
  },
  {
    "id": "market-14",
    "name": "Mercatino Napoli",
    "region": "Da classificare",
    "province": "",
    "city": "Napoli",
    "address": "Via Provinciale Montagna Spaccata, 421",
    "cap": "80126",
    "mail": "napolipianura@mercatopoli.it",
    "sqm": 600,
    "storeType": "Generalista",
    "itemsSold": 170,
    "kwhSaved": 2415,
    "co2Saved": 616,
    "treesEquivalent": 29,
    "reuseRate": 82,
    "categories": {
      "Arredo": 34,
      "Elettronica": 22,
      "Moda": 64,
      "Casa": 33,
      "Libri e giochi": 17
    }
  },
  {
    "id": "market-15",
    "name": "Mercatino Napoli",
    "region": "Da classificare",
    "province": "",
    "city": "Napoli",
    "address": "Via Eleonora Duse, 50",
    "cap": "80126",
    "mail": "info@portobelloroad.it",
    "sqm": 2000,
    "storeType": "Generalista",
    "itemsSold": 216,
    "kwhSaved": 3085,
    "co2Saved": 787,
    "treesEquivalent": 37,
    "reuseRate": 83,
    "categories": {
      "Arredo": 45,
      "Elettronica": 28,
      "Moda": 80,
      "Casa": 41,
      "Libri e giochi": 22
    }
  },
  {
    "id": "market-16",
    "name": "Mercatino Castel Maggiore",
    "region": "Emilia-Romagna",
    "province": "BO",
    "city": "Castel Maggiore",
    "address": "Via Massarenti, 2",
    "cap": "40013",
    "mail": "info@usaeriusacastelmaggiore.it",
    "sqm": 700,
    "storeType": "Generalista",
    "itemsSold": 135,
    "kwhSaved": 2099,
    "co2Saved": 535,
    "treesEquivalent": 25,
    "reuseRate": 73,
    "categories": {
      "Arredo": 40,
      "Elettronica": 19,
      "Moda": 41,
      "Casa": 22,
      "Libri e giochi": 13
    }
  },
  {
    "id": "market-17",
    "name": "Mercatino Forlì",
    "region": "Emilia-Romagna",
    "province": "FC",
    "city": "Forlì",
    "address": "Via Filanda, 8",
    "cap": "47121",
    "mail": "rovistiamo@gmail.com",
    "sqm": 395,
    "storeType": "Generalista",
    "itemsSold": 110,
    "kwhSaved": 1723,
    "co2Saved": 439,
    "treesEquivalent": 21,
    "reuseRate": 64,
    "categories": {
      "Arredo": 17,
      "Elettronica": 20,
      "Moda": 32,
      "Casa": 27,
      "Libri e giochi": 14
    }
  },
  {
    "id": "market-18",
    "name": "Mercatino Forlì",
    "region": "Emilia-Romagna",
    "province": "FC",
    "city": "Forlì",
    "address": "Via Po, 3",
    "cap": "47122",
    "mail": "fc01@kece.it",
    "sqm": 440,
    "storeType": "Generalista",
    "itemsSold": 113,
    "kwhSaved": 1752,
    "co2Saved": 447,
    "treesEquivalent": 21,
    "reuseRate": 65,
    "categories": {
      "Arredo": 18,
      "Elettronica": 20,
      "Moda": 33,
      "Casa": 27,
      "Libri e giochi": 15
    }
  },
  {
    "id": "market-19",
    "name": "Mercatino Forlì",
    "region": "Emilia-Romagna",
    "province": "FC",
    "city": "Forlì",
    "address": "Via Schiaparelli, 15/A",
    "cap": "47122",
    "mail": "usatofollia@gmail.com",
    "sqm": 1200,
    "storeType": "Generalista",
    "itemsSold": 146,
    "kwhSaved": 2241,
    "co2Saved": 571,
    "treesEquivalent": 27,
    "reuseRate": 66,
    "categories": {
      "Arredo": 24,
      "Elettronica": 25,
      "Moda": 42,
      "Casa": 35,
      "Libri e giochi": 20
    }
  },
  {
    "id": "market-20",
    "name": "Mercatino Parma",
    "region": "Emilia-Romagna",
    "province": "PR",
    "city": "Parma",
    "address": "Via Rapallo, 4/A",
    "cap": "43100",
    "mail": "info@mercatinodellusatopr.it",
    "sqm": 1400,
    "storeType": "Generalista",
    "itemsSold": 184,
    "kwhSaved": 2884,
    "co2Saved": 735,
    "treesEquivalent": 35,
    "reuseRate": 74,
    "categories": {
      "Arredo": 37,
      "Elettronica": 31,
      "Moda": 48,
      "Casa": 44,
      "Libri e giochi": 24
    }
  },
  {
    "id": "market-21",
    "name": "Mercatino Cento",
    "region": "Emilia-Romagna",
    "province": "FE",
    "city": "Cento",
    "address": "Via Ferrarese, 39",
    "cap": "44042",
    "mail": "cento@usatolandia.it",
    "sqm": 500,
    "storeType": "Generalista",
    "itemsSold": 123,
    "kwhSaved": 1808,
    "co2Saved": 461,
    "treesEquivalent": 22,
    "reuseRate": 82,
    "categories": {
      "Arredo": 39,
      "Elettronica": 13,
      "Moda": 29,
      "Casa": 27,
      "Libri e giochi": 15
    }
  },
  {
    "id": "market-22",
    "name": "Mercatino Idice",
    "region": "Emilia-Romagna",
    "province": "BO",
    "city": "Idice",
    "address": "Via Emilia Ponente, 492",
    "cap": "40068",
    "mail": "web@ilmercatinodifranzoni.it",
    "sqm": 500,
    "storeType": "Generalista",
    "itemsSold": 103,
    "kwhSaved": 1688,
    "co2Saved": 430,
    "treesEquivalent": 20,
    "reuseRate": 62,
    "categories": {
      "Arredo": 32,
      "Elettronica": 16,
      "Moda": 22,
      "Casa": 22,
      "Libri e giochi": 11
    }
  },
  {
    "id": "market-23",
    "name": "Mercatino Ferrara",
    "region": "Emilia-Romagna",
    "province": "FE",
    "city": "Ferrara",
    "address": "Via del Commercio, 11 (Zona Barco), Ferrara.",
    "cap": "44122",
    "mail": "ferrara@dituttodipiu.net",
    "sqm": 0,
    "storeType": "Generalista",
    "itemsSold": 106,
    "kwhSaved": 1722,
    "co2Saved": 439,
    "treesEquivalent": 21,
    "reuseRate": 69,
    "categories": {
      "Arredo": 30,
      "Elettronica": 17,
      "Moda": 26,
      "Casa": 22,
      "Libri e giochi": 11
    }
  },
  {
    "id": "market-24",
    "name": "Mercatino Reggio Emilia",
    "region": "Emilia-Romagna",
    "province": "RE",
    "city": "Reggio Emilia",
    "address": "Via Brigata Reggio, 24/F",
    "cap": "42124",
    "mail": "reggioemiliakennedy@mercatopoli.it",
    "sqm": 695,
    "storeType": "Generalista",
    "itemsSold": 141,
    "kwhSaved": 2323,
    "co2Saved": 592,
    "treesEquivalent": 28,
    "reuseRate": 78,
    "categories": {
      "Arredo": 37,
      "Elettronica": 25,
      "Moda": 41,
      "Casa": 24,
      "Libri e giochi": 14
    }
  },
  {
    "id": "market-25",
    "name": "Mercatino Forlì",
    "region": "Emilia-Romagna",
    "province": "FC",
    "city": "Forlì",
    "address": "Via E. Bertini, 98/4",
    "cap": "47122",
    "mail": "antichi.ricordi@yahoo.it",
    "sqm": 650,
    "storeType": "Generalista",
    "itemsSold": 120,
    "kwhSaved": 1873,
    "co2Saved": 478,
    "treesEquivalent": 23,
    "reuseRate": 63,
    "categories": {
      "Arredo": 31,
      "Elettronica": 18,
      "Moda": 31,
      "Casa": 26,
      "Libri e giochi": 14
    }
  },
  {
    "id": "market-26",
    "name": "Mercatino Bastiglia",
    "region": "Emilia-Romagna",
    "province": "MO",
    "city": "Bastiglia",
    "address": "Via Canaletto, 20/A",
    "cap": "41030",
    "mail": "info@houseofbikers.it",
    "sqm": 1500,
    "storeType": "Generalista",
    "itemsSold": 156,
    "kwhSaved": 2208,
    "co2Saved": 563,
    "treesEquivalent": 27,
    "reuseRate": 77,
    "categories": {
      "Arredo": 35,
      "Elettronica": 17,
      "Moda": 35,
      "Casa": 49,
      "Libri e giochi": 20
    }
  },
  {
    "id": "market-27",
    "name": "Mercatino Reggio nell'Emilia",
    "region": "Emilia-Romagna",
    "province": "RE",
    "city": "Reggio nell'Emilia",
    "address": "Via Brigata Reggio, 28/C",
    "cap": "42124",
    "mail": "reggioemiliakennedy@babybazar.it",
    "sqm": 200,
    "storeType": "Specializzato infanzia",
    "itemsSold": 152,
    "kwhSaved": 2323,
    "co2Saved": 592,
    "treesEquivalent": 28,
    "reuseRate": 82,
    "categories": {
      "Arredo": 26,
      "Elettronica": 25,
      "Moda": 45,
      "Casa": 38,
      "Libri e giochi": 18
    }
  },
  {
    "id": "market-28",
    "name": "Mercatino Reggio Emilia",
    "region": "Emilia-Romagna",
    "province": "RE",
    "city": "Reggio Emilia",
    "address": "Via Guicciardi, 12",
    "cap": "42122",
    "mail": "affareassicurato@gmail.com",
    "sqm": 620,
    "storeType": "Generalista",
    "itemsSold": 142,
    "kwhSaved": 2349,
    "co2Saved": 599,
    "treesEquivalent": 29,
    "reuseRate": 82,
    "categories": {
      "Arredo": 39,
      "Elettronica": 25,
      "Moda": 39,
      "Casa": 24,
      "Libri e giochi": 15
    }
  },
  {
    "id": "market-29",
    "name": "Mercatino Pordenone",
    "region": "Friuli-Venezia Giulia",
    "province": "PN",
    "city": "Pordenone",
    "address": "Via della Comina 15",
    "cap": "33170",
    "mail": "info@exusatomanonsolo.it",
    "sqm": 1500,
    "storeType": "Generalista",
    "itemsSold": 187,
    "kwhSaved": 3073,
    "co2Saved": 784,
    "treesEquivalent": 37,
    "reuseRate": 77,
    "categories": {
      "Arredo": 34,
      "Elettronica": 38,
      "Moda": 51,
      "Casa": 36,
      "Libri e giochi": 28
    }
  },
  {
    "id": "market-30",
    "name": "Mercatino Formia",
    "region": "Lazio",
    "province": "LT",
    "city": "Formia",
    "address": "Via Pastore, 5",
    "cap": "04023",
    "mail": "formia@mercatopoli.it",
    "sqm": 600,
    "storeType": "Generalista",
    "itemsSold": 113,
    "kwhSaved": 1734,
    "co2Saved": 442,
    "treesEquivalent": 21,
    "reuseRate": 58,
    "categories": {
      "Arredo": 26,
      "Elettronica": 17,
      "Moda": 30,
      "Casa": 26,
      "Libri e giochi": 14
    }
  },
  {
    "id": "market-31",
    "name": "Mercatino Ventimiglia",
    "region": "Liguria",
    "province": "IM",
    "city": "Ventimiglia",
    "address": "Via Hanbury, 5",
    "cap": "18039",
    "mail": "doriana.bottini@gmail.com",
    "sqm": 0,
    "storeType": "Generalista",
    "itemsSold": 116,
    "kwhSaved": 1692,
    "co2Saved": 431,
    "treesEquivalent": 21,
    "reuseRate": 83,
    "categories": {
      "Arredo": 28,
      "Elettronica": 15,
      "Moda": 35,
      "Casa": 23,
      "Libri e giochi": 15
    }
  },
  {
    "id": "market-32",
    "name": "Mercatino Chiavari",
    "region": "Liguria",
    "province": "GE",
    "city": "Chiavari",
    "address": "Via Santa Chiara 77/91",
    "cap": "16043",
    "mail": "almercatodellusatochiavari@gmail.com",
    "sqm": 880,
    "storeType": "Generalista",
    "itemsSold": 152,
    "kwhSaved": 2393,
    "co2Saved": 610,
    "treesEquivalent": 29,
    "reuseRate": 77,
    "categories": {
      "Arredo": 43,
      "Elettronica": 22,
      "Moda": 41,
      "Casa": 32,
      "Libri e giochi": 14
    }
  },
  {
    "id": "market-33",
    "name": "Mercatino Rapallo",
    "region": "Liguria",
    "province": "GE",
    "city": "Rapallo",
    "address": "Corso Goffredo Mameli, 202/U",
    "cap": "16035",
    "mail": "almercatodellusato@libero.it",
    "sqm": 400,
    "storeType": "Generalista",
    "itemsSold": 114,
    "kwhSaved": 1557,
    "co2Saved": 397,
    "treesEquivalent": 19,
    "reuseRate": 79,
    "categories": {
      "Arredo": 28,
      "Elettronica": 11,
      "Moda": 34,
      "Casa": 27,
      "Libri e giochi": 14
    }
  },
  {
    "id": "market-34",
    "name": "Mercatino Cocquio Trevisago",
    "region": "Lombardia",
    "province": "VA",
    "city": "Cocquio Trevisago",
    "address": "Via Milano, 90",
    "cap": "21034",
    "mail": "lapulcesnc@alice.it",
    "sqm": 1600,
    "storeType": "Generalista",
    "itemsSold": 142,
    "kwhSaved": 2192,
    "co2Saved": 559,
    "treesEquivalent": 27,
    "reuseRate": 56,
    "categories": {
      "Arredo": 28,
      "Elettronica": 23,
      "Moda": 40,
      "Casa": 34,
      "Libri e giochi": 17
    }
  },
  {
    "id": "market-35",
    "name": "Mercatino Legnano",
    "region": "Lombardia",
    "province": "MI",
    "city": "Legnano",
    "address": "Via Firenze, 2",
    "cap": "20025",
    "mail": "info@mercatinodellusato.it",
    "sqm": 1000,
    "storeType": "Generalista",
    "itemsSold": 144,
    "kwhSaved": 2046,
    "co2Saved": 522,
    "treesEquivalent": 25,
    "reuseRate": 84,
    "categories": {
      "Arredo": 39,
      "Elettronica": 15,
      "Moda": 41,
      "Casa": 33,
      "Libri e giochi": 16
    }
  },
  {
    "id": "market-36",
    "name": "Mercatino Cinisello Balsamo",
    "region": "Lombardia",
    "province": "MI",
    "city": "Cinisello Balsamo",
    "address": "Viale Valtellina,28",
    "cap": "20092",
    "mail": "antonioruggeri68@icloud.com",
    "sqm": 1100,
    "storeType": "Generalista",
    "itemsSold": 157,
    "kwhSaved": 2619,
    "co2Saved": 668,
    "treesEquivalent": 32,
    "reuseRate": 81,
    "categories": {
      "Arredo": 33,
      "Elettronica": 30,
      "Moda": 41,
      "Casa": 38,
      "Libri e giochi": 15
    }
  },
  {
    "id": "market-37",
    "name": "Mercatino Macerata",
    "region": "Marche",
    "province": "MC",
    "city": "Macerata",
    "address": "Via Weiden 27",
    "cap": "62100",
    "mail": "macerata@usatopiu.it",
    "sqm": 650,
    "storeType": "Generalista",
    "itemsSold": 143,
    "kwhSaved": 2257,
    "co2Saved": 576,
    "treesEquivalent": 27,
    "reuseRate": 77,
    "categories": {
      "Arredo": 40,
      "Elettronica": 21,
      "Moda": 39,
      "Casa": 30,
      "Libri e giochi": 13
    }
  },
  {
    "id": "market-38",
    "name": "Mercatino Casale Monferrato",
    "region": "Piemonte",
    "province": "AL",
    "city": "Casale Monferrato",
    "address": "Via Adam, 96",
    "cap": "15033",
    "mail": "info.bottegausato@gmail.com",
    "sqm": 1000,
    "storeType": "Generalista",
    "itemsSold": 151,
    "kwhSaved": 2536,
    "co2Saved": 647,
    "treesEquivalent": 31,
    "reuseRate": 79,
    "categories": {
      "Arredo": 30,
      "Elettronica": 30,
      "Moda": 40,
      "Casa": 36,
      "Libri e giochi": 15
    }
  },
  {
    "id": "market-39",
    "name": "Mercatino Bari",
    "region": "Puglia",
    "province": "BA",
    "city": "Bari",
    "address": "Stradella Deserto, 1",
    "cap": "70132",
    "mail": "baristanic@mercatopoli.it",
    "sqm": 1170,
    "storeType": "Generalista",
    "itemsSold": 175,
    "kwhSaved": 2745,
    "co2Saved": 700,
    "treesEquivalent": 33,
    "reuseRate": 84,
    "categories": {
      "Arredo": 46,
      "Elettronica": 27,
      "Moda": 55,
      "Casa": 30,
      "Libri e giochi": 17
    }
  },
  {
    "id": "market-40",
    "name": "Mercatino Foggia",
    "region": "Puglia",
    "province": "FG",
    "city": "Foggia",
    "address": "Via Lucera, 280",
    "cap": "71100",
    "mail": "portaportesedifoggia@gmail.com",
    "sqm": 800,
    "storeType": "Generalista",
    "itemsSold": 159,
    "kwhSaved": 2626,
    "co2Saved": 670,
    "treesEquivalent": 32,
    "reuseRate": 85,
    "categories": {
      "Arredo": 41,
      "Elettronica": 28,
      "Moda": 38,
      "Casa": 34,
      "Libri e giochi": 18
    }
  },
  {
    "id": "market-41",
    "name": "Mercatino Sassari",
    "region": "Sardegna",
    "province": "SS",
    "city": "Sassari",
    "address": "Via Mario De Candia, 4",
    "cap": "07100",
    "mail": "gliaffarituoi.sassari@gmail.com",
    "sqm": 900,
    "storeType": "Generalista",
    "itemsSold": 171,
    "kwhSaved": 2444,
    "co2Saved": 623,
    "treesEquivalent": 30,
    "reuseRate": 84,
    "categories": {
      "Arredo": 53,
      "Elettronica": 18,
      "Moda": 39,
      "Casa": 31,
      "Libri e giochi": 30
    }
  },
  {
    "id": "market-42",
    "name": "Mercatino Agrigento",
    "region": "Sicilia",
    "province": "AG",
    "city": "Agrigento",
    "address": "Via Mazzini Giuseppe, 205",
    "cap": "92100",
    "mail": "mercatinousatoagrigento@gmail.com",
    "sqm": 500,
    "storeType": "Generalista",
    "itemsSold": 108,
    "kwhSaved": 1713,
    "co2Saved": 437,
    "treesEquivalent": 21,
    "reuseRate": 71,
    "categories": {
      "Arredo": 27,
      "Elettronica": 17,
      "Moda": 32,
      "Casa": 23,
      "Libri e giochi": 9
    }
  },
  {
    "id": "market-43",
    "name": "Mercatino Sesto Fiorentino",
    "region": "Toscana",
    "province": "FI",
    "city": "Sesto Fiorentino",
    "address": "Via di Querceto, 89",
    "cap": "50019",
    "mail": "amministrazione@sesteseservizi.it",
    "sqm": 600,
    "storeType": "Generalista",
    "itemsSold": 147,
    "kwhSaved": 1950,
    "co2Saved": 497,
    "treesEquivalent": 24,
    "reuseRate": 80,
    "categories": {
      "Arredo": 34,
      "Elettronica": 13,
      "Moda": 42,
      "Casa": 38,
      "Libri e giochi": 20
    }
  },
  {
    "id": "market-44",
    "name": "Mercatino Bolzano",
    "region": "Trentino-Alto Adige",
    "province": "BZ",
    "city": "Bolzano",
    "address": "Via Albrecht Dürer, 30/A",
    "cap": "39100",
    "mail": "negoziousatobolzano@gmail.com",
    "sqm": 488,
    "storeType": "Generalista",
    "itemsSold": 146,
    "kwhSaved": 2230,
    "co2Saved": 569,
    "treesEquivalent": 27,
    "reuseRate": 76,
    "categories": {
      "Arredo": 25,
      "Elettronica": 24,
      "Moda": 44,
      "Casa": 36,
      "Libri e giochi": 17
    }
  },
  {
    "id": "market-45",
    "name": "Mercatino Este",
    "region": "Veneto",
    "province": "PD",
    "city": "Este",
    "address": "Via Leonardo da Vinci, 6G-6H",
    "cap": "35042",
    "mail": "mercatone.este@gmail.com",
    "sqm": 1500,
    "storeType": "Generalista",
    "itemsSold": 149,
    "kwhSaved": 2360,
    "co2Saved": 602,
    "treesEquivalent": 29,
    "reuseRate": 86,
    "categories": {
      "Arredo": 40,
      "Elettronica": 23,
      "Moda": 33,
      "Casa": 33,
      "Libri e giochi": 20
    }
  }
];
